### ISSUE TITLE
Invalid column name while deleting

### ISSUE THREAD

**Issue by caino** [zzzprojects/EntityFramework.Extended#174]
Hi,
I've three tables
Users [ID_User]
Products [ID_Product]
Norm_Prod_Us [ID_Norm_Prod_Us, ID_Product, ID_Us]

as you can see the primary key of Users table differs from the foreign key into Norm_Prod_Us and when I try to join the two table for a batch delete of users with some products EntityFramework.Extended generates the following query:

``` sql
DELETE [dbo].[Users]
FROM [dbo].[Users] AS j0 INNER JOIN (
SELECT 
   [Extent1].[ID_Product] AS [ID_Product], 
   [Extent1].[ID_Us] AS [ID_Us]
   FROM [dbo].[Norm_Prod_Us] AS [Extent1]
   WHERE ([Extent1].[ID_Us] IS NOT NULL) AND ([Extent1].[ID_Product] IS NOT NULL) AND ([Extent1].[ID_Product] IN (3681, 3682, 3683, 3684))
) AS j1 ON (j0.[ID_User] = j1.[ID_User])
```

That query throws a Sql exception Error 207: Invalid column name 'ID_User'.

We solved the issue using the Where clause instead of the Join.

Thank you for the support and with hope for a solution to give more confidence to that project.

caino

**Comment by xumix** [comment]
Same here for me.
```
DELETE [dbo].[IppOrganization]
FROM [dbo].[IppOrganization] AS j0 INNER JOIN (
SELECT 
    1 AS [C1], 
    CAST(NULL AS uniqueidentifier) AS [C2]
    FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
    WHERE 1 = 0
) AS j1 ON (j0.[Id] = j1.[Id])
```

**Comment by mlooise** [comment]
Same for me. Any solution=

UPDATE "agreements"."invoicing_track" AS j0
SET 
next_invoice = :p__update__0
FROM (
SELECT 
1 AS "C1",
"Project1"."C1" AS **"C2"**
FROM ( SELECT 
	"Extent1".id AS "C1"
	FROM invoicing_track AS "Extent1"
)  AS "Project1"
WHERE ("Project1"."C1" IN (59248,59249,59250,59251,59)) AND ("Project1"."C1" IS NOT NULL)
) as j1
WHERE (j0.id = j1.**id**)

**Comment by dsidirop** [comment]
Similar problem here with MS Sql Server 2014. In BatchDelete.cs the call to "query.GetCommandTextAndParameters()" returns the following snippet:

SELECT 
     CAST( [Extent1].[NSD_ID] AS bigint) AS [C1]
    FROM [dbo].[NB_STORED_FILTER_DEF] AS [Extent1]
    WHERE ( CAST( [Extent1].[NSD_STORED_FILTER_ID] AS bigint) IN (cast(16674 as bigint))) AND ( CAST( [Extent1].[NSD_STORED_FILTER_ID] AS bigint) IS NOT NULL)

This snippet gets plugged into {Select} inside 'CommandTextWhileTemplate' which looks like this:


DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP ({Top})
        FROM    A {Hint}
        FROM    {TableName} AS A
                INNER JOIN ( {Select}
                           ) AS B ON {PrimaryKeys}

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected

The resulting query looks like this:


DECLARE @rowAffected INT
DECLARE @totalRowAffected INT

SET @totalRowAffected = 0

WHILE @rowAffected IS NULL
    OR @rowAffected > 0
    BEGIN
        DELETE TOP (4000)
        FROM    A 
        FROM    [NIOBE].[NB_STORED_FILTER_DEF] AS A
                INNER JOIN ( SELECT 
     CAST( [Extent1].[NSD_ID] AS bigint) AS [C1]
    FROM [dbo].[NB_STORED_FILTER_DEF] AS [Extent1]
    WHERE ( CAST( [Extent1].[NSD_STORED_FILTER_ID] AS bigint) IN (cast(16674 as bigint))) AND ( CAST( [Extent1].[NSD_STORED_FILTER_ID] AS bigint) IS NOT NULL)
                           ) AS B ON A.[NSD_ID] = B.[NSD_ID]

        SET @rowAffected = @@ROWCOUNT
        SET @totalRowAffected = @totalRowAffected + @rowAffected
    END

SELECT  @totalRowAffected

There are two problems here:

- The bit that reads:

"FROM    [NIOBE].[NB_STORED_FILTER_DEF] AS A"

throws an error about "NB_STORED_FILTER_DEF" not getting found. I've changed it to

"FROM    [NIOBE].[dbo].[NB_STORED_FILTER_DEF] AS A"

and this part works.

- Inside 'BatchDelete.cs' the {PrimaryKeys} is evaluated into '[NSD_ID]' instead of [C1] and thus the column is not found. For this bit to work the correct syntax is:

AS B ON A.[NSD_ID] = B.[C1]

Sidenote: Using the lib to delete entries from the same table when it's being hosted in an oracle DB works. Going to look into it and see what I can dig up.

**Comment by JonathanMagnan** [comment]
Hello @dsidirop ,

This library is no longer supported since 2015.

I suggest you moving to our [Entity Framework Plus](http://entityframework-plus.net/) library.

Best Regards,

Jonathan
