### ISSUE TITLE
Batch Update - Oracle Error(ORA-00932: inconsistent datatypes: expected DATE got NUMBER)

### ISSUE THREAD

**Issue by jacksparrow47** [zzzprojects/EntityFramework.Extended#244]
Hi,
I try to set table uptm(last update time) column value to DateTime.Now but OracleBatchRunner throws "ORA-00932: inconsistent datatypes: expected DATE got NUMBER" exception. I have encounter this situation before, I guess this is result of OracleCommand bind parameter strategy . When I set BindByName property of Command value to true , Exception disappears

```
var property = updateCommand.GetType().GetProperty("BindByName");
                if (property != null)
                {
                    property.SetValue(updateCommand, true);
                }
```

**Comment by JonathanMagnan** [comment]
Hello @jacksparrow47 ,

This library is no longer supported since `2015`.

We recommend you to move to a supported library: http://entityframework-plus.net/

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by jacksparrow47** [comment]
I understand, thank you for answer
