### ISSUE TITLE
Explicitly resolve futures

### ISSUE THREAD

**Issue by Swoorup** [zzzprojects/EntityFramework.Extended#245]
Is there a reason, why decision was made to not resolve futures by not specifying explicitly, i.e instead of the first invocation of materializing(`ToList` or `AsEnumerable`), it could have something like: 

```CSharp
var postsFut = ctx.Posts.Future();
var ordersFut = ctx.Orders.Future();

ctx.Resolve(posts,orders);
// All future resolved explicitly at this point

var posts = postsFut.ToList();
var orders = ordersFut.ToList();
```

**Comment by JonathanMagnan** [comment]
Hello @Swoorup ,

This library is no longer supported since `2015`, I recommend you to switch to https://entityframework-plus.net/

I don't think there is any specific reason besides it works like `NHibernate`.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
